#!/bin/bash

set -euo pipefail

TIMES=$(cat $1)

# Cumulative time in seconds (CTS)
CTS=0

for time in $TIMES
do
  echo "Step time: $time"
  SUB='m'
  if [[ "$time" == *"$SUB"* ]]; then
    minutes="$( cut -d 'm' -f 1 <<< $time )"
    minute_seconds=$(expr $minutes \* 60)
    seconds=$(echo $time | sed 's/.*m//')
    CTS=$(($CTS + $minute_seconds + $seconds))
  fi

  SUB='h'
  if [[ "$time" == *"$SUB"* ]]; then
    hours="$( cut -d 'h' -f 1 <<< $time )"
    hour_seconds=$(expr $hours \* 3600)
    minutes=$(echo $time | sed 's/.*h//')
    minute_seconds=$(expr $minutes \* 60)
    CTS=$(($CTS + $hour_seconds + $minute_seconds))
  fi

  total_minutes=$(expr $CTS / 60)
  echo "Cumulative time: $CTS seconds"
  printf 'Cumulative time: %dh:%dm:%ds\n' $(($CTS/3600)) $(($CTS%3600/60)) $(($CTS%60))
  echo ""
done

total_minutes=$(expr $CTS / 60)
total_hours=$(expr $total_minutes / 60)

echo "Total seconds taken: $CTS"
printf 'Total time taken: %dh:%dm:%ds\n' $(($CTS/3600)) $(($CTS%3600/60)) $(($CTS%60))
