#!/bin/bash

set -euo pipefail

apps=(
    iterm2
    slack
    google-chrome
    monitorcontrol
    zoom
    docker
    kubectl
    notion
    visual-studio-code
)

brew install git

brew  install starship
echo \
    'eval "$(starship init zsh)"' \
>> ~/.zshrc

# Xcode tools
xcode-select --install

brew cask install --appdir="/Applications" ${apps[@]}
